"""
Mapeamento de campos para formulário PDF.
Este arquivo contém as definições de mapeamento entre os campos internos
da aplicação e os campos de formulário do PDF.
"""

# Informações Básicas — COM desconto (Página 11)
FORM_MAP_WITH_DESCONTO = {
    "nome_cliente":              "NOME com desc",
    "telefone_cliente":          "TELEFONE com desc",
    "email_cliente":             "E-MAIL com desc",
    "marca_carro":               "MARCA com desc",
    "modelo_carro":              "MODELO com desc",
    "teto_solar":                "TETO SOLAR com desc",
    "porta-malas":               "ABERTURA TAMPA DE MALA com desc",
    "tipo_documentacao":         "DOCUMENTACAO com desc",
    "desconto":                  "DESCONTO com desc",
    "vidro_10_anos":             "VALOR DA BLINDAGEM 1 com desc",
    "vidro_5_anos_18mm":         "CONFORT 18MM com desc",
    "vidro_5_anos_ultralight":   "ULTRA-LIGHT com desc",
    "pacote_revisao":            "TIPOS 6 com desc",
    "total_10_anos":             "VALOR DA BLINDAGEM 1 com desc",
    "total_18mm":                "VALOR DA BLINDAGEM 2 com desc",
    "total_ultralight":          "VALOR DA BLINDAGEM 3 com desc",
}

# Informações Básicas — SEM desconto (Página 11)
FORM_MAP_SEM_DESCONTO = {
    "nome_cliente":              "NOME sem desc",
    "telefone_cliente":          "TELEFONE sem desc",
    "email_cliente":             "E-MAIL sem desc",
    "marca_carro":               "MARCA sem desc",
    "modelo_carro":              "MODELO sem desc",
    "teto_solar":                "TETO SOLAR sem desc",
    "porta-malas":               "ABERTURA TAMPA DE MALA sem desc",
    "tipo_documentacao":         "DOCUMENTACAO sem desc",
    "vidro_10_anos":             "VALOR DA BLINDAGEM 1 sem desc",
    "vidro_5_anos_18mm":         "CONFORT 18MM sem desc",
    "vidro_5_anos_ultralight":   "ULTRA-LIGHT sem desc",
    "pacote_revisao":            "TIPOS 6 sem desc",
    "total_10_anos":             "VALOR DA BLINDAGEM 1 sem desc",
    "total_18mm":                "VALOR DA BLINDAGEM 2 sem desc",
    "total_ultralight":          "VALOR DA BLINDAGEM 3 sem desc",
}

# Condições de Pagamento (Página 12)
PAYMENT_CONDITIONS_MAP = {
    # — Comfort 10 Anos —
    "a_vista_10_anos":             "PARCELA 90 DIAS CONFORT 10 ANOS",
    "primeira_parcela_2x_10_anos": "1 PARCELA PARA 30 DIAS 1",
    "segunda_parcela_2x_10_anos":  "2 PARCELA PARA 30 DIAS 1",
    "total_2x_10_anos":            "TOTAL 2X 10 ANOS",
    "sinal_50_3x_10_anos":         "SINAL 50% 3X 10 ANOS",
    "primeira_parcela_3x_10_anos": "1 PARCELA 30 DIAS 3X 10 ANOS",
    "segunda_parcela_3x_10_anos":  "2 PARCELA 60 DIAS 3X 10 ANOS",
    "terceira_parcela_3x_10_anos": "3 PARCELA 90 DIAS 3X 10 ANOS",
    "total_3x_10_anos":            "TOTAL 3X 10 ANOS",
    "sinal_60_4x_10_anos":         "SINAL 60% 4X 10 ANOS",
    "primeira_parcela_4x_10_anos": "1 PARCELA 30 DIAS 4X 10 ANOS",
    "segunda_parcela_4x_10_anos":  "2 PARCELA 60 DIAS 4X 10 ANOS",
    "terceira_parcela_4x_10_anos": "3 PARCELA 90 DIAS 4X 10 ANOS",
    "quarta_parcela_4x_10_anos":   "4 PARCELA 120 DIAS 4X 10 ANOS",
    "total_4x_10_anos":            "TOTAL 4X 10 ANOS",
    "cartao_4_parcelas_10_anos":   "CARTAO 4 PARCELAS 10 ANOS",
    "cartao_5_parcelas_10_anos":   "CARTAO 5 PARCELAS 10 ANOS",
    "cartao_6_parcelas_10_anos":   "CARTAO 6 PARCELAS 10 ANOS",
    "cartao_7_parcelas_10_anos":   "CARTAO 7 PARCELAS 10 ANOS",
    "cartao_8_parcelas_10_anos":   "CARTAO 8 PARCELAS 10 ANOS",
    "cartao_9_parcelas_10_anos":   "CARTAO 9 PARCELAS 10 ANOS",
    "cartao_10_parcelas_10_anos":  "CARTAO 10 PARCELAS 10 ANOS",

    # — Comfort 18 mm —
    "a_vista_18mm":                "PARCELA 90 DIAS CONFORT 18MM",
    "primeira_parcela_2x_18mm":    "1 PARCELA PARA 30 DIAS 2",
    "segunda_parcela_2x_18mm":     "2 PARCELA PARA 30 DIAS 2",
    "total_2x_18mm":               "TOTAL 2X 18MM",
    "sinal_50_3x_18mm":            "SINAL 50% 3X 18MM",
    "primeira_parcela_3x_18mm":    "1 PARCELA 30 DIAS 3X 18MM",
    "segunda_parcela_3x_18mm":     "2 PARCELA 60 DIAS 3X 18MM",
    "terceira_parcela_3x_18mm":    "3 PARCELA 90 DIAS 3X 18MM",
    "total_3x_18mm":               "TOTAL 3X 18MM",
    "sinal_60_4x_18mm":            "SINAL 60% 4X 18MM",
    "primeira_parcela_4x_18mm":    "1 PARCELA 30 DIAS 4X 18MM",
    "segunda_parcela_4x_18mm":     "2 PARCELA 60 DIAS 4X 18MM",
    "terceira_parcela_4x_18mm":    "3 PARCELA 90 DIAS 4X 18MM",
    "quarta_parcela_4x_18mm":      "4 PARCELA 120 DIAS 4X 18MM",
    "total_4x_18mm":               "TOTAL 4X 18MM",
    "cartao_4_parcelas_18mm":      "CARTAO 4 PARCELAS 18MM",
    "cartao_5_parcelas_18mm":      "CARTAO 5 PARCELAS 18MM",
    "cartao_6_parcelas_18mm":      "CARTAO 6 PARCELAS 18MM",
    "cartao_7_parcelas_18mm":      "CARTAO 7 PARCELAS 18MM",
    "cartao_8_parcelas_18mm":      "CARTAO 8 PARCELAS 18MM",
    "cartao_9_parcelas_18mm":      "CARTAO 9 PARCELAS 18MM",
    "cartao_10_parcelas_18mm":     "CARTAO 10 PARCELAS 18MM",

    # — Ultralight —
    "a_vista_ultralight":          "PARCELA 90 DIAS ULTRA-LIGHT",
    "primeira_parcela_2x_ultralight": "1 PARCELA PARA 30 DIAS 3",
    "segunda_parcela_2x_ultralight":  "2 PARCELA PARA 30 DIAS 3",
    "total_2x_ultralight":         "TOTAL 2X ULTRALIGHT",
    "sinal_50_3x_ultralight":      "SINAL 50% 3X ULTRALIGHT",
    "primeira_parcela_3x_ultralight": "1 PARCELA 30 DIAS 3X ULTRALIGHT",
    "segunda_parcela_3x_ultralight":  "2 PARCELA 60 DIAS 3X ULTRALIGHT",
    "terceira_parcela_3x_ultralight": "3 PARCELA 90 DIAS 3X ULTRALIGHT",
    "total_3x_ultralight":         "TOTAL 3X ULTRALIGHT",
    "sinal_60_4x_ultralight":      "SINAL 60% 4X ULTRALIGHT",
    "primeira_parcela_4x_ultralight": "1 PARCELA 30 DIAS 4X ULTRALIGHT",
    "segunda_parcela_4x_ultralight":  "2 PARCELA 60 DIAS 4X ULTRALIGHT",
    "terceira_parcela_4x_ultralight": "3 PARCELA 90 DIAS 4X ULTRALIGHT",
    "quarta_parcela_4x_ultralight":   "4 PARCELA 120 DIAS 4X ULTRALIGHT",
    "total_4x_ultralight":        "TOTAL 4X ULTRALIGHT",
    "cartao_4_parcelas_ultralight":"CARTAO 4 PARCELAS ULTRALIGHT",
    "cartao_5_parcelas_ultralight":"CARTAO 5 PARCELAS ULTRALIGHT",
    "cartao_6_parcelas_ultralight":"CARTAO 6 PARCELAS ULTRALIGHT",
    "cartao_7_parcelas_ultralight":"CARTAO 7 PARCELAS ULTRALIGHT",
    "cartao_8_parcelas_ultralight":"CARTAO 8 PARCELAS ULTRALIGHT",
    "cartao_9_parcelas_ultralight":"CARTAO 9 PARCELAS ULTRALIGHT",
    "cartao_10_parcelas_ultralight":"CARTAO 10 PARCELAS ULTRALIGHT",
}
