"""
Mapeamento de campos para formulário PDF.
Este arquivo contém as definições de mapeamento entre os campos internos
da aplicação e os campos de formulário do PDF.
"""

# Informações Básicas — COM desconto (Página 11)
FORM_MAP_WITH_DESCONTO = {
    "nome_cliente":              "NOME",
    "telefone_cliente":          "TELEFONE",
    "email_cliente":             "E-MAIL",
    "marca_carro":               "MARCA",
    "modelo_carro":              "MODELO",
    "teto_solar":                "TETO SOLAR",
    "porta-malas":               "ABERTURA TAMPA DE MALA",
    "tipo_documentacao":         "DOCUMENTACAO",
    "desconto":                  "DESCONTO APLICADO",
    "vidro_10_anos":             "VALOR DA BLINDAGEM_2 1",
    "vidro_5_anos_18mm":         "VALOR DA BLINDAGEM_2 2",
    "vidro_5_anos_ultralight":   "VALOR DA BLINDAGEM_2 3",
    "pacote_revisao":            "TIPOS 6",
    "total_10_anos":             "CONFORT 10 ANOS_2 4",
    "total_18mm":                "CONFORT 18MM_2",
    "total_ultralight":          "ULTRA-LIGHT_2",
}

# Informações Básicas — SEM desconto (Página 11)
FORM_MAP_SEM_DESCONTO = {
    "nome_cliente":              "NOME sem desc",
    "telefone_cliente":          "TELEFONE sem desc",
    "email_cliente":             "E-MAIL sem desc",
    "marca_carro":               "MARCA sem desc",
    "modelo_carro":              "MODELO sem desc",
    "teto_solar":                "TETO SOLAR sem desc",
    "porta-malas":               "ABERTURA TAMPA DE MALA sem desc",
    "tipo_documentacao":         "DOCUMENTACAO sem desc",
    "vidro_10_anos":             "VALOR DA BLINDAGEM 1 sem desc",
    "vidro_5_anos_18mm":         "CONFORT 18MM sem desc",
    "vidro_5_anos_ultralight":   "ULTRA-LIGHT sem desc",
    "pacote_revisao":            "TIPOS 6 sem desc",
    "total_10_anos":             "VALOR DA BLINDAGEM 1 sem desc",
    "total_18mm":                "VALOR DA BLINDAGEM 2 sem desc",
    "total_ultralight":          "VALOR DA BLINDAGEM 3 sem desc",
}

# Condições de Pagamento (Página 12)
PAYMENT_CONDITIONS_MAP = {
    # — Comfort 10 Anos —
    "a_vista_10_anos":             "A VISTA 1",
    "primeira_parcela_2x_10_anos": "1 PARCELA PARA 30 DIAS 1",
    "segunda_parcela_2x_10_anos":  "2 PARCELAS  SEM JUROS 1",
    "total_2x_10_anos":            "SINAL 50 1",
    "sinal_50_3x_10_anos":         "SINAL 50_2 1",
    "primeira_parcela_3x_10_anos": "PARCELA 30 DIAS 1",
    "segunda_parcela_3x_10_anos":  "PARCELA 60 DIAS 1",
    "terceira_parcela_3x_10_anos": "3 PARCELAS  1 ACRÉSCIMO 1",
    "total_3x_10_anos":            "SINAL 60 1",
    "sinal_60_4x_10_anos":         "SINAL 60 1",
    "primeira_parcela_4x_10_anos": "PARCELA 30 DIAS_2 1",
    "segunda_parcela_4x_10_anos":  "PARCELA 60 DIAS_2 1",
    "terceira_parcela_4x_10_anos": "PARCELA 90 DIAS 1",
    "quarta_parcela_4x_10_anos":   "4 PARCELAS  3 ACRÉSCIMO 1",
    "total_4x_10_anos":            "4 PARCELAS  6 DE ACRÉSCIMO 1",
    "cartao_4_parcelas_10_anos":   "4 PARCELAS  6 DE ACRÉSCIMO 1",
    "cartao_5_parcelas_10_anos":   "5 PARCELAS  7 DE ACRÉSCIMO 1",
    "cartao_6_parcelas_10_anos":   "6 PARCELAS  8 DE ACRÉSCIMO 1",
    "cartao_7_parcelas_10_anos":   "7 PARCELAS  9 DE ACRÉSCIMO 1",
    "cartao_8_parcelas_10_anos":   "8 PARCELAS  10 DE ACRÉSCIMO 1",
    "cartao_9_parcelas_10_anos":   "9 PARCELAS  11 DE ACRÉSCIMO 1",
    "cartao_10_parcelas_10_anos":  "10 PARCELAS  12 DE ACRÉSCIMO 1",

    # — Comfort 18 mm —
    "a_vista_18mm":                "A VISTA 2",
    "primeira_parcela_2x_18mm":    "1 PARCELA PARA 30 DIAS 2",
    "segunda_parcela_2x_18mm":     "2 PARCELAS  SEM JUROS 2",
    "total_2x_18mm":               "SINAL 50 2",
    "sinal_50_3x_18mm":            "SINAL 50_2 2",
    "primeira_parcela_3x_18mm":    "PARCELA 30 DIAS 2",
    "segunda_parcela_3x_18mm":     "PARCELA 60 DIAS 2",
    "terceira_parcela_3x_18mm":    "3 PARCELAS  1 ACRÉSCIMO 2",
    "total_3x_18mm":               "SINAL 60 2",
    "sinal_60_4x_18mm":            "SINAL 60 2",
    "primeira_parcela_4x_18mm":    "PARCELA 30 DIAS_2 2",
    "segunda_parcela_4x_18mm":     "PARCELA 60 DIAS_2 2",
    "terceira_parcela_4x_18mm":    "PARCELA 90 DIAS 2",
    "quarta_parcela_4x_18mm":      "4 PARCELAS  3 ACRÉSCIMO 2",
    "total_4x_18mm":               "4 PARCELAS  6 DE ACRÉSCIMO 2",
    "cartao_4_parcelas_18mm":      "4 PARCELAS  6 DE ACRÉSCIMO 2",
    "cartao_5_parcelas_18mm":      "5 PARCELAS  7 DE ACRÉSCIMO 2",
    "cartao_6_parcelas_18mm":      "6 PARCELAS  8 DE ACRÉSCIMO 2",
    "cartao_7_parcelas_18mm":      "7 PARCELAS  9 DE ACRÉSCIMO 2",
    "cartao_8_parcelas_18mm":      "8 PARCELAS  10 DE ACRÉSCIMO 2",
    "cartao_9_parcelas_18mm":      "9 PARCELAS  11 DE ACRÉSCIMO 2",
    "cartao_10_parcelas_18mm":     "10 PARCELAS  12 DE ACRÉSCIMO 2",

    # — Ultralight —
    "a_vista_ultralight":          "A VISTA 3",
    "primeira_parcela_2x_ultralight": "1 PARCELA PARA 30 DIAS 3",
    "segunda_parcela_2x_ultralight":  "2 PARCELAS  SEM JUROS 3",
    "total_2x_ultralight":         "SINAL 50 3",
    "sinal_50_3x_ultralight":      "SINAL 50_2 3",
    "primeira_parcela_3x_ultralight": "PARCELA 30 DIAS 3",
    "segunda_parcela_3x_ultralight":  "PARCELA 60 DIAS 3",
    "terceira_parcela_3x_ultralight": "3 PARCELAS  1 ACRÉSCIMO 3",
    "total_3x_ultralight":         "SINAL 60 3",
    "sinal_60_4x_ultralight":      "SINAL 60 3",
    "primeira_parcela_4x_ultralight": "PARCELA 30 DIAS_2 3",
    "segunda_parcela_4x_ultralight":  "PARCELA 60 DIAS_2 3",
    "terceira_parcela_4x_ultralight": "PARCELA 90 DIAS 3",
    "quarta_parcela_4x_ultralight":   "4 PARCELAS  3 ACRÉSCIMO 3",
    "total_4x_ultralight":        "4 PARCELAS  6 DE ACRÉSCIMO 3",
    "cartao_4_parcelas_ultralight":"4 PARCELAS  6 DE ACRÉSCIMO 3",
    "cartao_5_parcelas_ultralight":"5 PARCELAS  7 DE ACRÉSCIMO 3",
    "cartao_6_parcelas_ultralight":"6 PARCELAS  8 DE ACRÉSCIMO 3",
    "cartao_7_parcelas_ultralight":"7 PARCELAS  9 DE ACRÉSCIMO 3",
    "cartao_8_parcelas_ultralight":"8 PARCELAS  10 DE ACRÉSCIMO 3",
    "cartao_9_parcelas_ultralight":"9 PARCELAS  11 DE ACRÉSCIMO 3",
    "cartao_10_parcelas_ultralight":"10 PARCELAS  12 DE ACRÉSCIMO 3",
}
